services:
  activemq:
    build: .
    container_name: broker-lab
    ports:
      - "8161:8161"     # Consola Web (Suele estar libre)
      - "61613:61613"   # STOMP (Fundamental)
      - "51611:61611"   # ANTES 61611 -> AHORA 51611
      - "51614:61614"   # ANTES 61614 -> AHORA 51614
      - "51616:61616"   # OpenWire alternativo
    environment:
      - ACTIVEMQ_ADMIN_USER=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: unless-stopped
  python-lab:
    image: python:3.14-slim
    container_name: cliente-python
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && tail -f /dev/null"
    # Inyectamos las variables del archivo .env al sistema operativo del contenedor
    environment:
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_USER=${BROKER_USER}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - QUEUE_VALIDADOS=${QUEUE_VALIDADOS}
      - QUEUE_ERRORES=${QUEUE_ERRORES}
    depends_on:
      - activemq