services:
  activemq:
    build: .
    container_name: broker-lab
    ports:
      # Panel de Administración Web
      - "8161:8161"
      # Protocolo OpenWire (JMS)
      - "61616:61616"
      # Protocolo STOMP (Para los scripts de Python)
      - "61613:61613"
      # Protocolo MQTT (Opcional, para IoT)
      - "1883:1883"
    environment:
      - ACTIVEMQ_ADMIN_USER=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: unless-stopped
  python-lab:
    image: python:3.14-slim
    container_name: cliente-python
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && tail -f /dev/null"
    depends_on:
      - activemq